@extends('registration')
@section('header')
@section('content')
    <script type="text/javascript" src="{{asset('js/preFormCreation.js')}}"></script>
    <?php
    if(session('message')){
        echo '<div id="floatingMessage">' . session('message') . '</div>';
    }
    ?>
    <div id="fichaFrontier">
    <div id='descCurso'>
        <p>Ayudas y Subvenciones</p>
    </div>
    <div class='imgCurso'>
        <a href=""><img src="{{asset('images/Transparencia.jpg')}}"></a>
        </div>
    </div>
    <div class="fichaDiv" id="presentacion">
        <p>En esta sección encontrarás toda la información en materia de Ayudas y Subvenciones de CENTRO DE HOSTELERÍA Y TURISMO DE CANARIAS SL.<br>
 
<br>Además, en la parte inferior de la pantalla encontrarás todos los enlaces a todas las convocatorias a los que hace referencia la siguiente información. <br>

<br>CENTRO DE HOSTELERÍA Y TURISMO DE CANARIAS SL.<br>

<br><br>FORMACIÓN DESEMPLEADOS (FPE)<br>
<br>•	FPE 2018 RESOLUCIÓN DEFINITIVA DE LA SUBDIRECCIÓN DE FORMACIÓN DE CONCESIÓN DE LAS SUBVENCIONES PUBLICADA EN EL TABLÓN DE ANUNCIOS DEL SCE EL 14 DICIEMBRE, EN RELACIÓN A LA RESOLUCIÓN 07 DE JUNIO DE 2018, DE LA PRESIDENTA, POR LA QUE SE APRUEBA LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES DESTINADAS A LA REALIZACIÓN DE ACCIONES FORMATIVAS DIRIGIDAS PRIORITARIAMENTE A TRABAJADORES/AS DESEMPLEADOS/AS INCLUIDAS EN LA PROGRAMACIÓN 2018 (BOC nº 118 de 20/06/2018) IMPORTE:590.625,00€<br>
<br><br>PLANES DE FORMACIÓN DIRIGIDOS PRIORITARIAMENTE PARA TRABAJADORES/AS OCUPADOS DE LA COMUNIDAD AUTÓNOMA DE CANARIAS A TRAVÉS DEL SERVICIO CANARIO DE EMPLEO
<br>•	EXPTE: FC-2018.2/06./1715280 PLANES DE FORMACION DIRIGIDOS PRIORITARIAMENTE A TRABAJADORES/ TRABAJADORAS OCUPADOS IMPORTE ECONÓMICO (142.580,00€) RESOLUCIÓN DE 30/07/2018 (EXTRACTO PUBLICADO EN BOC nº 153 DE 08/08/2018) PLAN HOSTELERIA<br>
<br>•	EXPTE: FC-2018.2/02/1715283 PLANES DE FORMACION DIRIGIDOS PRIORITARIAMENTE A TRABAJADORES/ TRABAJADORAS OCUPADOS IMPORTE ECONÓMICO (123.760,00€) RESOLUCIÓN DE 30/07/2018 (EXTRACTO PUBLICADO EN BOC nº 153 DE 08/08/2018) PLAN INDUSTRIA ALIMENTARIA<br>
<br><br>PLANES DE FORMACIÓN CON COMPROMISO DE CONTRATACIÓN A TRAVÉS DEL SERVICIO CANARIO DE EMPLEO<br>
Los itinerarios formativos asignados fueron los siguientes:<br>
<br>•	2018 – CENTRO DE FORMACIÓN DE HOSTELERÍA Y TURISMO DE CANARIAS, fue beneficiario de una la subvención a través de Resolución Nº 7391/2018 de la Dirección del SCE por la que se resuelve la concesión de subvenciones de las solicitudes presentadas en el segundo periodo de la convocatoria de concesión de subvenciones destinadas a la financiación de Programas formativos con compromiso de contratación para el ejercicio 2018, aprobadas mediante resolución de 19 de Abril de 2018, de la Presidenta (BOC nº 82, de 27 de abril de 2018) por importe de 388.557,48€<br>

<br>•	2019 – RESOLUCIÓN DE LA PRESIDENCIA DEL SERVICIO CANARIO DE EMPLEO POR LA QUE SE APRUEBA LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES, DESTINADAS A LA FINANCIACIÓN DE PROGRAMAS FORMATIVOS CON COMPROMISO DE 
CONTRATACIÓN DIRIGIDOS A PERSONAS DESEMPLEADAS PARA EL EJERCICIO 2019. (PUBLICADO EN BOC 69 DE 5 DE ABRIL DE 2019). IMPORTE: 391.135,40 €.<br>
<br>•	2019 – CONVOCATORIA DE INCENTIVOS A LA CONTRATACIÓN DE COLECTIVOS DE DIFÍCIL INSERCIÓN. EJE 1 DE LA LÍNEA ESTRATÉGICA 3 “APOYO A LA EMPLEABILIDAD” DEL FONDO DE DESARROLLO DE CANARIAS (FDCAN). ANUALIDAD 2019. CABILDO DE GRAN CANARIA (PUBLICADO EN EL BOP DE LAS PALMAS 39 DE 1 DE ABRIL DE 2019). IMPORTE: 4.000,00 €.<br>
<br>•	2019 – CONVOCATORIA DE INCENTIVOS A LA CONTRATACIÓN DE COLECTIVOS DE DIFÍCIL INSERCIÓN. EJE 1 DE LA LÍNEA ESTRATÉGICA 3 “APOYO A LA EMPLEABILIDAD” DEL FONDO DE DESARROLLO DE CANARIAS (FDCAN). ANUALIDAD 2019. CABILDO DE GRAN CANARIA (PUBLICADO EN EL BOP DE LAS PALMAS 39 DE 1 DE ABRIL DE 2019). IMPORTE: 3.000,00 €.<br>
<br>•	2019 – GC CONVOCATORIA DE INCENTIVOS A LA CONTRATACIÓN DE COLECTIVOS DE DIFÍCIL INSERCIÓN. EJE 1 DE LA LÍNEA ESTRATÉGICA 3 “APOYO A LA EMPLEABILIDAD” DEL FONDO DE DESARROLLO DE CANARIAS (FDCAN). ANUALIDAD 2019. CABILDO DE GRAN CANARIA (PUBLICADO EN EL BOP DE LAS PALMAS 39 DE 1 DE ABRIL DE 2019). IMPORTE: 4.000,00 €<br>
<br>•	2019 – RESOLUCIÓN DE LA DIRECCIÓN DEL SERVICIO CANARIO DE EMPLEO, DE INCREMENTO DE LA DOTACIÓN ECONÓMICA DE LA CONVOCATORIA PARA LA CONCESIÓN DE SUBVENCIONES DESTINADAS A LA REALIZACIÓN DE ACCIONES FORMATIVAS DIRIGIDAS PRIORITARIAMENTE A PERSONAS TRABAJADORAS DESEMPLEADAS INCLUIDAS EN LA PROGRAMACIÓN 2019, APROBADA MEDIANTE RESOLUCIÓN DE LA PRESIDENCIA DEL SERVICIO CANARIO DE EMPLEO DE FECHA 05 DE JULIO DE 2019, Y SE DA PUBLICIDAD AL CRÉDITO MÁXIMO DISPONIBLE. (PUBLICADO EN EL BOC 245 DE 19 DE DICIEMBRE DE 2019). FPED 2019. IMPORTE: 542.250,00 €<br>
<br>•	2020 - AVALES A FINANCIACIÓN A EMPRESAS Y AUTÓNOMOS CONCEDIDOS POR EL MINISTERIO DE ASUNTOS ECONÓMICOS Y TRANSFORMACIÓN DIGITAL PARA PALIAR EFECTOS DEL COVID19, GESTIONADOS POR EL ICO POR CUENTA DEL MINISTERIO. ARTÍCULO 29 RDL 8/2020. IMPORTE: 53.364,51 €.<br>
<br>•	2020 - CONVOCATORIA DE SUBVENCIONES PARA ACCIONES FORMATIVAS PRIORITARIAMENTE A DESEMPLEADOS FPED 2020. (PUBLICADO EN EL BOC 161 DE 11 DE AGOSTO DE 2020). IMPORTE: 578.913,00 €<br>
<br>•	2021 - CONCESIÓN DE LÍNEA COVID DE AYUDAS DIRECTAS A PERSONAS AUTÓNOMAS Y EMPRESAS TITULO I RDL 5_2021. (EXPEDIENTE EXP-SUBPYMES2-10791-2021). IMPORTE: 710.258,67 €.<br>
<br>•	2021 - RESOLUCIÓN DE LA DIRECCIÓN DEL SERVICIO CANARIO DE EMPLEO POR LA QUE SE RESUELVE LA CONCESIÓN DE SUBVENCIONES A LAS ENTIDADES FORMATIVAS QUE HAN PRESENTADO SOLICITUD EN EL SEGUNDO PERIODO DE LA CONVOCATORIA DE CONCESIÓN DE SUBVENCIONES DESTINADAS A LA FINANCIACIÓN DE PROGRAMAS FORMATIVOS CON COMPROMISO DE CONTRATACIÓN PARA EL EJERCICIO 2021. IMPORTE: 275.92,00 €.<br>
<br>•	2021 - RESOLUCIÓN DE LA DIRECCIÓN DEL SERVICIO CANARIO DE EMPLEO, DE INCREMENTO DE LA DOTACIÓN ECONÓMICA DE LA CONVOCATORIA PARA EL EJERCICIO PRESUPUESTARIO 2021, DE CONCESIÓN DE SUBVENCIONES PÚBLICAS, PARA LA EJECUCIÓN DE PLANES DE FORMACIÓN DIRIGIDOS PRIORITARIAMENTE A PERSONAS TRABAJADORAS OCUPADAS, APROBADA MEDIANTE RESOLUCIÓN NUM. 7745/2021, DE FECHA 10 DE SEPTIEMBRE, DE LA PRESIDENCIA DEL SERVICIO CANARIO DE EMPLEO Y SE DA PUBLICIDAD AL CRÉDITO MÁXIMO DISPONIBLE. EXP: FC-2021.2/04/1906105 /7/1/2021-0921124752. IMPORTE: 75.191,40 €.<br>
<br>•	2021 - RESOLUCIÓN DE LA DIRECCIÓN DEL SERVICIO CANARIO DE EMPLEO, DE INCREMENTO DE LA DOTACIÓN ECONÓMICA DE LA CONVOCATORIA PARA EL EJERCICIO PRESUPUESTARIO 2021, DE CONCESIÓN DE SUBVENCIONES PÚBLICAS, PARA LA EJECUCIÓN DE PLANES DE FORMACIÓN DIRIGIDOS PRIORITARIAMENTE A PERSONAS TRABAJADORAS OCUPADAS, APROBADA MEDIANTE RESOLUCIÓN NUM. 7745/2021, DE FECHA 10 DE SEPTIEMBRE, DE LA PRESIDENCIA DEL SERVICIO CANARIO DE EMPLEO Y SE DA PUBLICIDAD AL CRÉDITO MÁXIMO DISPONIBLE. EXP: FC-2021.2/04/1906105 /7/1/2021-0921124752. IMPORTE: 60.241,50 €.<br>
<br>•	2021 - RESOLUCIÓN DE LA DIRECCIÓN DEL SERVICIO CANARIO DE EMPLEO, DE INCREMENTO DE LA DOTACIÓN ECONÓMICA DE LA CONVOCATORIA PARA EL EJERCICIO PRESUPUESTARIO 2021, DE CONCESIÓN DE SUBVENCIONES PÚBLICAS, PARA LA EJECUCIÓN DE PLANES DE FORMACIÓN DIRIGIDOS PRIORITARIAMENTE A PERSONAS TRABAJADORAS OCUPADAS, APROBADA MEDIANTE RESOLUCIÓN NUM. 7745/2021, DE FECHA 10 DE SEPTIEMBRE, DE LA PRESIDENCIA DEL SERVICIO CANARIO DE EMPLEO Y SE DA PUBLICIDAD AL CRÉDITO MÁXIMO DISPONIBLE. EXP: FC-2021.2/05/1906119 /8/1/2021-0921124752. IMPORTE: 8.457,26 €.<br>
<br>•	2021 - RESOLUCIÓN DE LA DIRECCIÓN DEL SERVICIO CANARIO DE EMPLEO, DE INCREMENTO DE LA DOTACIÓN ECONÓMICA DE LA CONVOCATORIA PARA EL EJERCICIO PRESUPUESTARIO 2021, DE CONCESIÓN DE SUBVENCIONES PÚBLICAS, PARA LA EJECUCIÓN DE PLANES DE FORMACIÓN DIRIGIDOS PRIORITARIAMENTE A PERSONAS TRABAJADORAS OCUPADAS, APROBADA MEDIANTE RESOLUCIÓN NUM. 7745/2021, DE FECHA 10 DE SEPTIEMBRE, DE LA PRESIDENCIA DEL SERVICIO CANARIO DE EMPLEO Y SE DA PUBLICIDAD AL CRÉDITO MÁXIMO DISPONIBLE. EXP: FC-2021.2/05/1906119 /8/1/2021-0921124752. IMPORTE: 52.237,35 €<br>
<br>•	2021 - RESOLUCIÓN DE LA DIRECCIÓN DEL SERVICIO CANARIO DE EMPLEO, DE INCREMENTO DE LA DOTACIÓN ECONÓMICA DE LA CONVOCATORIA PARA EL EJERCICIO PRESUPUESTARIO 2021, DE CONCESIÓN DE SUBVENCIONES PÚBLICAS, DESTINADAS A LA REALIZACIÓN DE ACCIONES FORMATIVAS DIRIGIDAS PRIORITARIAMENTE A PERSONAS TRABAJADORAS DESEMPLEADAS INCLUIDAS EN LA PROGRAMACIÓN 2021, APROBADA MEDIANTE RESOLUCIÓN NUM. 6934/2021, DE FECHA 17 DE AGOSTO, DE LA PRESIDENCIA DEL SERVICIO CANARIO DE EMPLEO Y SE DA PUBLICIDAD AL CRÉDITO MÁXIMO DISPONIBLE. IMPORTE: 397.059,00 €.<br>



<br><br>Enlaces:<br>
<br><b><a href="{{asset('files/Ocupados2018.pdf')}}" target="_blank">• Ocupados 2018</a> <br><br>  <a href="{{asset('files/FPED2018.pdf')}}" target="_blank">• Asignación FPED 2018</a> <br><br> <a href="{{asset('files/FPED2019.pdf')}}" target="_blank">• Asignación FPED 2019</a><br><br><br></b></p>
    </div>
    <script type="text/javascript" src="{{asset('js/resizeText.js')}}"></script>
@stop
@section('footer')